name: Azure Blob Storage action'
description: "Upload or download blobs from an Azure Storage Account"
branding:
  icon: "archive"
  color: "green"
inputs:
  direction:
    description: "Specifies if you want to 'upload' or 'download' a blob"
    required: true
    default: "download"
  connection_string:
    description: "Specifies the connection string of the Azure Storage account to use"
    required: true
    default: ""
  container:
    description: "Specifies the container name of your Azure Storage account to use"
    required: true
    default: ""
  blob_path:
    description: "Specifies the path or file of the blob in your Azure Storage account"
    required: true
    default: ""
  local_path:
    description: "Specifies the path or file on the local machine"
    required: false
    default: "./"
runs:
  using: "docker"
  image: "Dockerfile"
